### ISSUE TITLE
miss static directory after building

### ISSUE THREAD

**Issue by valaxy** [appium/appium-express#7]
When running `npm install -g appium` & `appium`, shell report these errors:

    λ appium
    Error: ENOENT: no such file or directory, stat 'C:\Users\****\AppData\Roaming\npm\node_modules\appium\node_modules\appium-express\build\static\favicon.ico'
        at Error (native)
        at Object.fs.statSync (fs.js:892:18)
        ......

I didn't dig into depper, just report this issue, is there any condition where the directory `appium-express/static` not be copied to  `appium-express/build/static` after running build command

**Comment by Jonahss** [comment]
Hm... could you repost this issue to the main appium repo? we're trying to consolidate issues there.

Can you also post the versions of Node and npm you ran the install with?
